const STATUS=["Solicitação","Em criação","Em análise","Ajustes","Aprovado","Na gráfica","Concluído"];
const KEY="graficarm_demands_v1";
const API_URL=(window.GRAFICARM_CONFIG?.apiUrl||"").trim();
const MAX_FILE_SIZE=8*1024*1024;
const seed=[
{id:"RM-0001",name:"Sitru",category:"Outros",city:"Geral",priority:"Alta",status:"Em criação",deadline:"2026-08-10",owner:"Criação",notes:"Confirmar nomenclatura, formato, tiragem e finalidade do material.",link:""},
{id:"RM-0002",name:"Adesivo bola 30 × 30 cm",category:"Adesivo",city:"Geral",priority:"Alta",status:"Em criação",deadline:"2026-08-11",owner:"Criação",notes:"Conferir limite legal, faca, acabamento e quantidade.",link:""},
{id:"RM-0003",name:"Adesivo moto 12 × 12 cm",category:"Adesivo",city:"Geral",priority:"Alta",status:"Em criação",deadline:"2026-08-11",owner:"Criação",notes:"Peça para mobilização. Definir tiragem.",link:""},
{id:"RM-0004",name:"Adesivo para-choque 30 × 10 cm",category:"Adesivo",city:"Geral",priority:"Alta",status:"Em criação",deadline:"2026-08-11",owner:"Criação",notes:"Conferir legibilidade, acabamento e tiragem.",link:""},
{id:"RM-0005",name:"Santinho — Montes Claros",category:"Impresso",city:"Montes Claros",priority:"Urgente",status:"Em criação",deadline:"2026-08-09",owner:"Criação",notes:"Mensagem: A força do Norte que Minas precisa e a Odonto merece.",link:""},
{id:"RM-0006",name:"Santinho — Januária",category:"Impresso",city:"Januária",priority:"Urgente",status:"Em criação",deadline:"2026-08-09",owner:"Criação",notes:"Mensagem em validação: Januarense vota em Jaguarense. Revisar termo antes da aprovação.",link:""},
{id:"RM-0007",name:"Santinho — Bonito de Minas",category:"Impresso",city:"Bonito de Minas",priority:"Alta",status:"Em criação",deadline:"2026-08-10",owner:"Criação",notes:"Definir mensagem regional e tiragem.",link:""},
{id:"RM-0008",name:"Colinha",category:"Impresso",city:"Geral",priority:"Média",status:"Em criação",deadline:"2026-08-13",owner:"Criação",notes:"Definir formato, conteúdo, quantidade e estratégia de distribuição.",link:""},
{id:"RM-0009",name:"Santinho — Quem é Raphael",category:"Impresso",city:"Geral",priority:"Alta",status:"Em criação",deadline:"2026-08-10",owner:"Criação",notes:"Peça biográfica com mensagem acessível e objetiva.",link:""},
{id:"RM-0010",name:"Santão 15 × 21 cm",category:"Impresso",city:"Geral",priority:"Média",status:"Em criação",deadline:"2026-08-13",owner:"Criação",notes:"Definir conteúdo, frente e verso, papel e tiragem.",link:""},
{id:"RM-0011",name:"WindBanners",category:"Sinalização",city:"Geral",priority:"Alta",status:"Em criação",deadline:"2026-08-12",owner:"Criação",notes:"Informar quantidade, dimensões, locais de uso e fornecedor.",link:""},
{id:"RM-0012",name:"Lonas — Comitê Montes Claros",category:"Comitê",city:"Montes Claros",priority:"Urgente",status:"Em criação",deadline:"2026-08-09",owner:"Criação",notes:"Medir todos os vãos antes do fechamento. Conferir limites aplicáveis à fachada.",link:""},
{id:"RM-0013",name:"Carta aos Dentistas",category:"Impresso",city:"Minas Gerais",priority:"Alta",status:"Em criação",deadline:"2026-08-12",owner:"Redação / Criação",notes:"Fechar texto, segmentação, envelope, selo e estratégia de distribuição.",link:""}
].map(x=>({...x,checks:{text:false,legal:false,print:false,approval:false},createdAt:new Date().toISOString()}));
let demands=load(),activeView="dashboard",draggedId=null,syncing=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{const d=JSON.parse(localStorage.getItem(KEY));return Array.isArray(d)&&d.length?d:structuredClone(seed)}catch{return structuredClone(seed)}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(demands));renderAll()}
function syncLabel(text,state=""){const el=$("#syncStatus");if(!el)return;el.textContent=text;el.dataset.state=state}
async function api(action,payload={}){
  if(!API_URL)throw new Error("Integração ainda não publicada");
  const body=new URLSearchParams({action,payload:JSON.stringify(payload)});
  const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body});
  if(!res.ok)throw new Error(`Falha de conexão (${res.status})`);
  const data=await res.json();
  if(!data.ok)throw new Error(data.error||"A Central recusou a operação");
  return data;
}
async function refreshFromCentral(){
  if(!API_URL){syncLabel("Configuração da sincronização pendente","pending");return}
  try{syncLabel("Sincronizando…","loading");const data=await api("list");demands=data.demands||[];saveLocal();syncLabel("Sincronizado com a Central","ok")}
  catch(err){syncLabel("Sem conexão — cópia local ativa","error");toast(err.message)}
}
async function persistDemand(demand,file){
  if(!API_URL){saveLocal();syncLabel("Dados locais — integração pendente","pending");return {local:true}}
  syncing=true;syncLabel("Salvando…","loading");
  try{const data=await api("save",{demand,file});if(data.demand)Object.assign(demand,data.demand);saveLocal();syncLabel("Sincronizado com a Central","ok");return data}
  finally{syncing=false}
}
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function formatDate(v){if(!v)return"Sem prazo";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(v+"T12:00:00Z")).replace(".","")}
function badgeClass(s){return s==="Ajustes"?"adjust":s==="Aprovado"?"approved":s==="Na gráfica"?"print":s==="Concluído"?"done":""}
function matches(d){const q=$("#globalSearch").value.toLowerCase();return !q||[d.name,d.city,d.category,d.owner,d.notes].join(" ").toLowerCase().includes(q)}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function go(view){activeView=view;$$(".view").forEach(x=>x.classList.toggle("active",x.id===view));$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));const titles={dashboard:"Visão geral",kanban:"Quadro de produção",library:"Biblioteca de materiais",calendar:"Calendário",suppliers:"Fornecedores"};$("#pageTitle").textContent=titles[view];$("#sidebar").classList.remove("open");renderAll()}
function renderStats(){const open=demands.filter(d=>d.status!=="Concluído").length,analysis=demands.filter(d=>d.status==="Em análise").length,approved=demands.filter(d=>["Aprovado","Na gráfica","Concluído"].includes(d.status)).length,urgent=demands.filter(d=>d.priority==="Urgente"&&!["Concluído"].includes(d.status)).length;$("#stats").innerHTML=[[open,"Demandas abertas","Em todas as etapas","accent"],[analysis,"Em análise","Aguardando conferência","warn"],[approved,"Aprovados","Liberados no fluxo","ok"],[urgent,"Prioridade urgente","Exigem atenção","danger"]].map(([v,l,d,c])=>`<div class="stat ${c}"><div class="label">${l}</div><div class="value">${v}</div><div class="detail">${d}</div></div>`).join("")}
function renderDashboard(){renderStats();const max=Math.max(1,...STATUS.map(s=>demands.filter(d=>d.status===s).length));$("#statusChart").innerHTML=STATUS.map(s=>{const n=demands.filter(d=>d.status===s).length;return `<div class="status-row"><span>${s}</span><div class="track"><span style="width:${n/max*100}%"></span></div><b>${n}</b></div>`}).join("");const priorities=demands.filter(d=>d.priority==="Urgente"||d.priority==="Alta").sort((a,b)=>(a.deadline||"9").localeCompare(b.deadline||"9")).slice(0,5);$("#urgentList").innerHTML=priorities.length?priorities.map(d=>`<div class="urgent-item" data-open="${d.id}"><i class="priority-dot ${d.priority==="Urgente"?"urgent":""}"></i><div><strong>${esc(d.name)}</strong><span>${esc(d.city)} · ${esc(d.status)}</span></div><time>${formatDate(d.deadline)}</time></div>`).join(""):'<p>Nenhuma prioridade no momento.</p>';$("#recentTable").innerHTML=demands.slice().reverse().slice(0,6).map(d=>`<tr data-open="${d.id}"><td>${esc(d.name)}</td><td>${esc(d.city)}</td><td>${esc(d.owner)}</td><td>${formatDate(d.deadline)}</td><td><span class="badge ${badgeClass(d.status)}">${d.status}</span></td></tr>`).join("")}
function card(d){return `<article class="demand-card" draggable="true" data-id="${d.id}" data-open="${d.id}"><div class="card-top"><h4>${esc(d.name)}</h4><span class="priority ${d.priority}">${d.priority}</span></div><div class="card-meta"><span class="tag">${esc(d.city)}</span><span class="tag">${esc(d.category)}</span></div><div class="card-footer"><span>${esc(d.id)}</span><span>Prazo ${formatDate(d.deadline)}</span></div></article>`}
function renderKanban(){const p=$("#filterPriority").value,c=$("#filterCity").value;$("#kanbanBoard").innerHTML=STATUS.map(s=>{const ds=demands.filter(d=>d.status===s&&(!p||d.priority===p)&&(!c||d.city===c)&&matches(d));return `<section class="kanban-column" data-status="${s}"><div class="column-head"><span>${s}</span><b>${ds.length}</b></div><div class="card-list">${ds.map(card).join("")}</div></section>`}).join("");$$(".demand-card").forEach(el=>{el.addEventListener("dragstart",e=>{draggedId=el.dataset.id;el.classList.add("dragging");e.stopPropagation()});el.addEventListener("dragend",()=>el.classList.remove("dragging"))});$$(".kanban-column").forEach(col=>{col.addEventListener("dragover",e=>{e.preventDefault();col.classList.add("drop-over")});col.addEventListener("dragleave",()=>col.classList.remove("drop-over"));col.addEventListener("drop",async e=>{e.preventDefault();col.classList.remove("drop-over");const d=demands.find(x=>x.id===draggedId);if(d&&d.status!==col.dataset.status){const previous=d.status;d.status=col.dataset.status;saveLocal();try{const result=await persistDemand(d,null);toast(result.local?"Etapa salva neste navegador":"Etapa atualizada")}catch(err){d.status=previous;saveLocal();syncLabel("Falha ao sincronizar","error");toast(err.message)}}})})}
function renderLibrary(){const cat=$("#filterCategory").value,st=$("#filterStatus").value;const ds=demands.filter(d=>(!cat||d.category===cat)&&(!st||d.status===st)&&matches(d));$("#libraryCount").textContent=`${ds.length} material(is)`;$("#libraryGrid").innerHTML=ds.map(d=>`<article class="library-card" data-open="${d.id}"><div class="thumb"><span>${esc(d.category.toUpperCase())}</span></div><div class="library-body"><h3>${esc(d.name)}</h3><p>${esc(d.notes||"Sem observações cadastradas.")}</p><div class="library-foot"><span class="tag">${esc(d.city)}</span><span class="badge ${badgeClass(d.status)}">${d.status}</span></div></div></article>`).join("")}
function renderCalendar(){const ds=demands.filter(d=>d.deadline&&d.status!=="Concluído").sort((a,b)=>a.deadline.localeCompare(b.deadline));$("#calendarList").innerHTML=ds.length?ds.map(d=>`<div class="calendar-item" data-open="${d.id}"><time>${formatDate(d.deadline)}</time><div><strong>${esc(d.name)}</strong><p>${esc(d.city)} · ${esc(d.owner)}</p></div><span class="badge ${badgeClass(d.status)}">${d.status}</span></div>`).join(""):'<div class="empty-state"><p>Nenhum prazo cadastrado.</p></div>'}
function renderFilters(){const cities=[...new Set(demands.map(d=>d.city).filter(Boolean))].sort(),cats=[...new Set(demands.map(d=>d.category).filter(Boolean))].sort();const cv=$("#filterCity").value,catv=$("#filterCategory").value,stv=$("#filterStatus").value;$("#filterCity").innerHTML='<option value="">Todas as cidades</option>'+cities.map(x=>`<option>${esc(x)}</option>`).join("");$("#filterCategory").innerHTML='<option value="">Todas as categorias</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join("");$("#filterStatus").innerHTML='<option value="">Todos os status</option>'+STATUS.map(x=>`<option>${x}</option>`).join("");$("#filterCity").value=cv;$("#filterCategory").value=catv;$("#filterStatus").value=stv}
function renderAll(){renderFilters();renderDashboard();renderKanban();renderLibrary();renderCalendar();bindOpen()}
function bindOpen(){$$("[data-open]").forEach(el=>el.onclick=e=>{if(e.defaultPrevented)return;openModal(el.dataset.open)})}
function openModal(id){const d=demands.find(x=>x.id===id);$("#demandForm").reset();$("#filePreview").innerHTML="";$("#demandId").value=d?.id||"";$("#modalTitle").textContent=d?"Editar demanda":"Nova demanda";$("#demandStatus").innerHTML=STATUS.map(s=>`<option>${s}</option>`).join("");if(d){$("#demandName").value=d.name;$("#demandCategory").value=d.category;$("#demandCity").value=d.city;$("#demandPriority").value=d.priority;$("#demandStatus").value=d.status;$("#demandDeadline").value=d.deadline||"";$("#demandOwner").value=d.owner||"";$("#demandRequester").value=d.requester||"";$("#demandFormat").value=d.format||"";$("#demandQuantity").value=d.quantity||"";$("#demandNotes").value=d.notes||"";$("#demandLink").value=d.link||"";["cmyk","dpi","bleed","margin","fonts","legal","pdf","proof"].forEach(k=>$("#check"+k[0].toUpperCase()+k.slice(1)).checked=!!d.checks?.[k])}$("#demandModal").hidden=false}
function closeModal(){$("#demandModal").hidden=true}
function nextId(){const n=Math.max(0,...demands.map(d=>Number(d.id.replace(/\D/g,""))||0))+1;return "RM-"+String(n).padStart(4,"0")}
function filePayload(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);if(file.size>MAX_FILE_SIZE)return reject(new Error("O arquivo excede o limite de 8 MB"));const allowed=["image/jpeg","image/png","image/webp","application/pdf"];if(!allowed.includes(file.type))return reject(new Error("Envie uma imagem JPG, PNG, WebP ou PDF"));const reader=new FileReader();reader.onload=()=>resolve({name:file.name,mime:file.type,base64:String(reader.result).split(",")[1]});reader.onerror=()=>reject(new Error("Não foi possível ler o arquivo"));reader.readAsDataURL(file)})}
$("#demandForm").onsubmit=async e=>{e.preventDefault();if(syncing)return;const id=$("#demandId").value||nextId(),old=demands.find(d=>d.id===id);const data={id,name:$("#demandName").value.trim(),category:$("#demandCategory").value,city:$("#demandCity").value.trim()||"Geral",format:$("#demandFormat").value.trim(),priority:$("#demandPriority").value,status:$("#demandStatus").value,deadline:$("#demandDeadline").value,owner:$("#demandOwner").value.trim()||"A definir",requester:$("#demandRequester").value.trim(),quantity:$("#demandQuantity").value.trim(),notes:$("#demandNotes").value.trim(),link:$("#demandLink").value.trim(),checks:Object.fromEntries(["cmyk","dpi","bleed","margin","fonts","legal","pdf","proof"].map(k=>[k,$("#check"+k[0].toUpperCase()+k.slice(1)).checked])),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};try{const file=await filePayload($("#demandFile").files[0]);if(old)Object.assign(old,data);else demands.push(data);saveLocal();const result=await persistDemand(old||data,file);closeModal();toast(result.local?"Salva neste navegador — integração pendente":old?"Demanda atualizada":"Demanda criada")}catch(err){syncLabel("Falha ao sincronizar","error");toast(err.message)}}
$("#demandFile").onchange=e=>{const f=e.target.files[0],p=$("#filePreview");p.innerHTML="";if(!f)return;if(f.size>MAX_FILE_SIZE){e.target.value="";toast("O arquivo excede o limite de 8 MB");return}if(f.type.startsWith("image/")){const img=document.createElement("img");img.src=URL.createObjectURL(f);p.appendChild(img)}else p.textContent="PDF selecionado: "+f.name;toast("O arquivo será enviado ao Drive ao salvar")}
$$("[data-close]").forEach(x=>x.onclick=closeModal);$("#demandModal").onclick=e=>{if(e.target===$("#demandModal"))closeModal()};$("#newDemand").onclick=()=>openModal();$("#mobileMenu").onclick=()=>$("#sidebar").classList.toggle("open");$$(".nav-item").forEach(x=>x.onclick=()=>go(x.dataset.view));$$("[data-go]").forEach(x=>x.onclick=()=>go(x.dataset.go));$("#supplierInfo").onclick=()=>window.open("https://docs.google.com/spreadsheets/d/1bDb2u_s19E2JMJd73J_ovP-l59bs5LCRkdNM2YgpJ6c/edit","_blank");["filterPriority","filterCity","filterCategory","filterStatus"].forEach(id=>$("#"+id).onchange=renderAll);$("#globalSearch").oninput=renderAll;document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
renderAll();refreshFromCentral();
